adding:
  dependencies:
    config:
      - field.field.node.landing.field_meta_tags
    module:
      - metatag
  content:
    field_meta_tags:
      type: metatag_empty_formatter
      label: above
      settings: {  }
      third_party_settings: {  }
      weight: 108
      region: content
removing: {  }
