<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implementa hook_form_alter().
 */
function template_config_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == "node_advanced_page_edit_form") {

    $form['field_enlace_cta']['#states'] = [
        'visible' => [
          ':input[name="field_select_header_design"]' => ['value' => 'long'],
        ],
      ];
  }
}